export const enum_mob = {
	ecureuils_enrages: 1,
	petite_araignee: 2,
	chat_sauvage: 3,
	chaton_onirique: 4,
	chauve_souris: 5,
	escargot_geant: 6,
	furet: 7,
	grande_abeille: 8,
	lapin: 9,
	poule: 10,
	rat: 11,
	ane: 12,
	cadavre_ensanglante: 13,
	cerf: 14,
	charpie: 15,
	chat_onirique: 16,
	chevre: 17,
	cochon: 18,
	coupe_jarret: 19,
	felpa_mineure: 20,
	gnoll: 21,
	incendiaire: 22,
	kobold: 23,
	masse_terreuse: 24,
	mouton: 25,
	petite_plante_carnivore: 26,
	serpent: 27,
	squelette: 28,
	mega_gob_musikos: 29,
	grand_slaad: 30,
	loup_errant: 31,
	scorpion: 32,
	vache: 33,
	araignee_de_sang: 34,
	archer_squelette: 35,
	artefact_negation: 36,
	bandit_elfe: 37,
	bandit_humain: 38,
	bandit_orc: 39,
	chat_ideonirique: 40,
	coeur_negation: 41,
	flammeche_destruction: 42,
	germe_vitalite: 43,
	gnoll_sanglant: 44,
	gobelin: 45,
	goule: 46,
	harpie: 47,
	kobold_alchimiste: 48,
	kobold_glace: 49,
	kobold_forgepierre: 50,
	marin_kalabe: 51,
	nain: 52,
	necromancien_solitaire: 53,
	pumbah: 54,
	reflet_alteration: 55,
	sanglier: 56,
	serpent_eau: 57,
	shak: 58,
	skaven: 59,
	slaad_mineur: 60,
	slaad_mineur_gris: 61,
	slaad_mineur_vert: 62,
	squelette_forcene: 63,
	svrisslish_troll_glaces: 64,
	tekumbo: 65,
	troll: 66,
	zombi: 67,
	loup_blanc: 68,
	arachnide_maudit: 69,
	araignee_brune: 70,
	archer_origur: 71,
	archer_gobelin: 72,
	assassin: 73,
	bison: 74,
	capitaine_kalabe: 75,
	chef_guerre_gnoll: 76,
	chef_bandits: 77,
	colosse_ossements: 78,
	colosse_chair: 79,
	felpa_majeure: 80,
	garde_slaad: 81,
	grognard: 82,
	grunt_origur: 83,
	guerrier_squelette: 84,
	harpie_dechiqueteuse: 85,
	harpie_mort_vivante: 86,
	hobgobelin: 87,
	homme_lezard: 88,
	jeune_cyclope: 89,
	mage_squelette: 90,
	nain_hache: 91,
	nain_masse: 92,
	nain_marteau: 93,
	plante_carnivore: 94,
	shaman_gobelin: 95,
	slaad_mort_vivant: 96,
	sorciere: 97,
	troll_glace: 98,
	zombi_infecte: 99,
	borgho: 100,
	archer_hobgobelin: 101,
	chef_guerre_gnoll_sanglant: 102,
	chef_guerre_kobold: 103,
	chef_origur: 104,
	chevaucheur_gobelin: 105,
	colosse_chair_deux_tetes: 106,
	dragonnet: 107,
	duelliste: 108,
	esprit_gemissant: 109,
	golem_argile: 110,
	golem_fer: 111,
	grand_serpent_eau: 112,
	grande_araignee_noire: 113,
	guerrier_hobgobelin: 114,
	harpie_reine: 115,
	homme_poisson: 116,
	homme_rat: 117,
	jeune_ogre: 118,
	lueur_alteration: 119,
	mage_duelliste: 120,
	meandre_vitalite: 121,
	momie: 122,
	ours: 123,
	shaman_hobgobelin: 124,
	slaad: 125,
	slaad_gris: 126,
	slaad_vert: 127,
	spirale_negation: 128,
	squelette_infernal: 129,
	tornade_flamme: 130,
	troll_cavernes: 131,
	garde_slaad_majeur: 132,
	champion_squelette_geant: 133,
	cyclope: 134,
	fossoyeur: 135,
	geant: 136,
	geant_mort_vivant: 137,
	golem_karkh: 138,
	grosse_plante_carnivore: 139,
	homme_lezard_geant: 140,
	meduse: 141,
	necromancien_sanctifie: 142,
	ombre_marais: 143,
	serpent_roches: 144,
	slaad_majeur_rouge: 145,
	troll_blanc: 146,
	ver_geant_marais: 147,
	araignee_titanesque: 148,
	cyclope_eclope: 149,
	dragon_rouge: 150,
	golem_roche: 151,
	maraudeur_sylvestre: 152,
	mirage_alteration: 153,
	ogre: 154,
	ouragan_feu: 155,
	petit_olimorse_enrage: 156,
	pieuvre_geante: 157,
	slaad_majeur_gris: 158,
	slaad_majeur_vert: 159,
	spire_vitalite: 160,
	terreur_marais: 161,
	vortex_negation: 162,
	basilic: 163,
	bern_hartapy: 164,
	champion_karkh: 165,
	chef_gobelin: 166,
	geant_champion: 167,
	grolehm: 168,
	necromancien: 169,
	spectre_abysses: 170,
	troll_geant: 171,
	chef_chevaucheurs_gobelins: 172,
	devoreur_sables: 173,
	gardien_gisements: 174,
	geant_deux_tetes: 175,
	geant_deux_tetes_mort_vivant: 176,
	grand_dracosire_rouge: 177,
	roi_hobgobelin: 178,
	slaad_superieur_gris: 179,
	slaad_superieur_vert: 180,
	spectre_effroi: 181,
	kraken: 182,
	leviathan: 183,
	maitre_necromancien: 184,
	olimorse_enrage: 185,
	seigneur_mort: 186,
	liche: 187,
	ToString: (value: number): string | undefined => {
		const str = [
			undefined,
			'Écureuils Enragés',
			'Petite Araignée',
			'Chat Sauvage',
			'Chaton Onirique',
			'Chauve-souris',
			'Escargot Géant',
			'Furet',
			'Grande Abeille',
			'Lapin',
			'Poule',
			'Rat',
			'Âne',
			'Cadavre Ensanglanté',
			'Cerf',
			'Charpie',
			'Chat Onirique',
			'Chèvre',
			'Cochon',
			'Coupe-jarret',
			'Felpa Mineure',
			'Gnoll',
			'Incendiaire',
			'Kobold',
			'Masse Terreuse',
			'Mouton',
			'Petite Plante Carnivore',
			'Serpent',
			'Squelette',
			"Mega'gob Musikos",
			'Grand Slaad',
			'Loup Errant',
			'Scorpion',
			'Vache',
			'Araignée de Sang',
			'Archer Squelette',
			'Artefact de la Négation',
			'Bandit Elfe',
			'Bandit Humain',
			'Bandit Orc',
			'Chat Idéonirique',
			'Cœur de Négation',
			'Flammèche de la Destruction',
			'Germe de Vitalité',
			'Gnoll Sanglant',
			'Gobelin',
			'Goule',
			'Harpie',
			'Kobold Alchimiste',
			'Kobold de Glace',
			'Kobold Forgepierre',
			'Marin Kalabé',
			'Nain',
			'Nécromancien Solitaire',
			'Pumbah',
			"Reflet de l'Altération",
			'Sanglier',
			"Serpent d'Eau",
			'Shak',
			'Skaven',
			'Slaad Mineur',
			'Slaad Mineur Gris',
			'Slaad Mineur Vert',
			'Squelette Forcené',
			"Svri'sslish Troll des Glaces",
			'Tekumbo',
			'Troll',
			'Zombi',
			'Loup Blanc',
			'Arachnide Maudit',
			'Araignée Brune',
			'Archer Origur',
			'Archer Gobelin',
			'Assassin',
			'Bison',
			'Capitaine Kalabé',
			'Chef de Guerre Gnoll',
			'Chef des Bandits',
			"Colosse d'Ossements",
			'Colosse de Chair',
			'Felpa Majeure',
			'Garde du Slaad',
			'Grognard',
			'Grunt Origur',
			'Guerrier Squelette',
			'Harpie Déchiqueteuse',
			'Harpie Morte-vivante',
			'Hobgobelin',
			'Homme-Lézard',
			'Jeune Cyclope',
			'Mage Squelette',
			'Nain à la Hache',
			'Nain à la Masse',
			'Nain au Marteau',
			'Plante Carnivore',
			'Shaman Gobelin',
			'Slaad Mort-vivant',
			'Sorcière',
			'Troll des Glaces',
			'Zombi Infecté',
			'Borgho',
			'Archer Hobgobelin',
			'Chef de Guerre Gnoll Sanglant',
			'Chef de Guerre Kobold',
			'Chef Origur',
			'Chevaucheur Gobelin',
			'Colosse de Chair à Deux Têtes',
			'Dragonnet',
			'Duelliste',
			'Esprit Gémissant',
			"Golem d'Argile",
			'Golem de Fer',
			"Grand Serpent d'Eau",
			'Grande Araignée Noire',
			'Guerrier Hobgobelin',
			'Harpie Reine',
			'Homme-Poisson',
			'Homme-Rat',
			'Jeune Ogre',
			"Lueur de l'Altération",
			'Mage Duelliste',
			'Méandre de Vitalité',
			'Momie',
			'Ours',
			'Shaman Hobgobelin',
			'Slaad',
			'Slaad Gris',
			'Slaad Vert',
			'Spirale de la Négation',
			'Squelette Infernal',
			'Tornade de Flamme',
			'Troll des Cavernes',
			'Garde Majeur du Slaad',
			'Champion Squelette Géant',
			'Cyclope',
			'Fossoyeur',
			'Géant',
			'Géant Mort-vivant',
			'Golem de Karkh',
			'Grosse Plante Carnivore',
			'Homme-Lézard Géant',
			'Méduse',
			'Nécromancien Sanctifié',
			'Ombre du Marais',
			'Serpent des Roches',
			'Slaad Majeur Rouge',
			'Troll Blanc',
			'Ver Géant du Marais',
			'Araignée Titanesque',
			'Cyclope Estropié',
			'Dragon Rouge',
			'Golem de Roche',
			'Maraudeur Sylvestre',
			"Mirage de l'Altération",
			'Ogre',
			'Ouragan de Feu',
			'Petit Olimorse Enragé',
			'Pieuvre Géante',
			'Slaad Majeur Gris',
			'Slaad Majeur Vert',
			'Spire de Vitalité',
			'Terreur du Marais',
			'Vortex de la Négation',
			'Basilic',
			'Bern Hartapy',
			'Champion de Karkh',
			'Chef Gobelin',
			'Géant Champion',
			'Grolehm',
			'Nécromancien',
			'Spectre des Abysses',
			'Troll Géant',
			'Chef des Chevaucheurs Gobelins',
			'Dévoreur de Sables',
			'Gardien des Gisements',
			'Géant à Deux Têtes',
			'Géant à Deux Têtes Mort-vivant',
			'Grand Dracosire Rouge',
			'Roi Hobgobelin',
			'Slaad Supérieur Gris',
			'Slaad Supérieur Vert',
			"Spectre de l'Effroi",
			'Kraken',
			'Léviathan',
			'Maître Nécromancien',
			'Olimorse Enragé',
			'Seigneur Mort',
			'Liche',
		];
		return str[value];
	},
};

export const enum_mob_picture = {
	[enum_mob.ecureuils_enrages]: 'https://ideo-lejeu.com/ideov23/creatures/ecureuil_petit.png',
	[enum_mob.petite_araignee]: 'https://ideo-lejeu.com/ideov23/creatures/petitearaignee.gif',
	[enum_mob.chat_sauvage]: 'https://ideo-lejeu.com/ideov23/creatures/Chat_noir.gif',
	[enum_mob.chaton_onirique]: 'https://ideo-lejeu.com/ideov23/creatures/Chaton.png',
	[enum_mob.chauve_souris]: 'https://ideo-lejeu.com/ideov23/creatures/chauve_souris.gif',
	[enum_mob.escargot_geant]: 'https://ideo-lejeu.com/ideov23/creatures/escargot_dragon.gif',
	[enum_mob.furet]: 'https://ideo-lejeu.com/ideov23/creatures/furet.gif',
	[enum_mob.grande_abeille]: 'https://ideo-lejeu.com/ideov23/creatures/abeille.gif',
	[enum_mob.lapin]: 'https://ideo-lejeu.com/ideov23/creatures/lapin.png',
	[enum_mob.poule]: 'https://ideo-lejeu.com/ideov23/creatures/poule.png',
	[enum_mob.rat]: 'https://ideo-lejeu.com/ideov23/creatures/rat.gif',
	[enum_mob.ane]: 'https://ideo-lejeu.com/ideov23/creatures/ane.gif',
	[enum_mob.cadavre_ensanglante]: 'https://ideo-lejeu.com/ideov23/creatures/zombie.gif',
	[enum_mob.cerf]: 'https://ideo-lejeu.com/ideov23/creatures/cerf.gif',
	[enum_mob.charpie]: 'https://ideo-lejeu.com/ideov23/creatures/harpie.gif',
	[enum_mob.chat_onirique]: 'https://ideo-lejeu.com/ideov23/creatures/Chaton_Chapeau.png',
	[enum_mob.chevre]: 'https://ideo-lejeu.com/ideov23/creatures//new/chevre.gif',
	[enum_mob.cochon]: 'https://ideo-lejeu.com/ideov23/creatures/cochon.png',
	[enum_mob.coupe_jarret]: 'https://ideo-lejeu.com/ideov23/creatures/coupe_jarret.gif',
	[enum_mob.felpa_mineure]: 'https://ideo-lejeu.com/ideov23/creatures/felpa.gif',
	[enum_mob.gnoll]: 'https://ideo-lejeu.com/ideov23/creatures/gnoll.gif',
	[enum_mob.incendiaire]: 'https://ideo-lejeu.com/ideov23/creatures/incendiaire.gif',
	[enum_mob.kobold]: 'https://ideo-lejeu.com/ideov23/creatures/kobold.gif',
	[enum_mob.masse_terreuse]: 'https://ideo-lejeu.com/ideov23/creatures/tas_boue.png',
	[enum_mob.mouton]: 'https://ideo-lejeu.com/ideov23/creatures/mouton.png',
	[enum_mob.petite_plante_carnivore]: 'https://ideo-lejeu.com/ideov23/creatures/ptt_plante_carnivore.png',
	[enum_mob.serpent]: 'https://ideo-lejeu.com/ideov23/creatures/serpent_s.gif',
	[enum_mob.squelette]: 'https://ideo-lejeu.com/ideov23/creatures/skelet.gif',
	[enum_mob.mega_gob_musikos]: 'https://ideo-lejeu.com/ideov23/creatures/chef_gobelin.gif',
	[enum_mob.grand_slaad]: 'https://ideo-lejeu.com/ideov23/creatures/geant_dragon_vert.gif',
	[enum_mob.loup_errant]: 'https://ideo-lejeu.com/ideov23/creatures/loup.gif',
	[enum_mob.scorpion]: 'https://ideo-lejeu.com/ideov23/creatures/scorpion.gif',
	[enum_mob.vache]: 'https://ideo-lejeu.com/ideov23/creatures/vache.png',
	[enum_mob.araignee_de_sang]: 'https://ideo-lejeu.com/ideov23/creatures/araignee.gif',
	[enum_mob.archer_squelette]: 'https://ideo-lejeu.com/ideov23/creatures/archer-squelette.gif',
	[enum_mob.artefact_negation]: 'https://ideo-lejeu.com/ideov23/creatures/artefactneg.gif',
	[enum_mob.bandit_elfe]: 'https://ideo-lejeu.com/ideov23/creatures/pnj/pe_archer.gif',
	[enum_mob.bandit_humain]: 'https://ideo-lejeu.com/ideov23/creatures/bandit.gif',
	[enum_mob.bandit_orc]: 'https://ideo-lejeu.com/ideov23/creatures/bandit_orc.gif',
	[enum_mob.chat_ideonirique]: 'https://ideo-lejeu.com/ideov23/creatures/Chaton_Chapeau_Mariniere.png',
	[enum_mob.coeur_negation]: 'https://ideo-lejeu.com/ideov23/creatures/miniN.gif',
	[enum_mob.flammeche_destruction]: 'https://ideo-lejeu.com/ideov23/creatures/miniD.gif',
	[enum_mob.germe_vitalite]: 'https://ideo-lejeu.com/ideov23/creatures/miniV.gif',
	[enum_mob.gnoll_sanglant]: 'https://ideo-lejeu.com/ideov23/creatures/gnoll_yrs.gif',
	[enum_mob.gobelin]: 'https://ideo-lejeu.com/ideov23/creatures/gobelin.png',
	[enum_mob.goule]: 'https://ideo-lejeu.com/ideov23/creatures/goule.png',
	[enum_mob.harpie]: 'https://ideo-lejeu.com/ideov23/creatures/harpie.png',
	[enum_mob.kobold_alchimiste]: 'https://ideo-lejeu.com/ideov23/creatures/kobold_alchimiste.png',
	[enum_mob.kobold_glace]: 'https://ideo-lejeu.com/ideov23/creatures/kobold_de_glace.png',
	[enum_mob.kobold_forgepierre]: 'https://ideo-lejeu.com/ideov23/creatures/kobold_forgepierre.png',
	[enum_mob.marin_kalabe]: 'https://ideo-lejeu.com/ideov23/creatures/marin_kalabe.png',
	[enum_mob.nain]: 'https://ideo-lejeu.com/ideov23/creatures/nain.png',
	[enum_mob.necromancien_solitaire]: 'https://ideo-lejeu.com/ideov23/creatures/necromancien_solitaire.png',
	[enum_mob.pumbah]: 'https://ideo-lejeu.com/ideov23/creatures/pumbah.png',
	[enum_mob.reflet_alteration]: 'https://ideo-lejeu.com/ideov23/creatures/reflet_dalteration.png',
	[enum_mob.sanglier]: 'https://ideo-lejeu.com/ideov23/creatures/sanglier.png',
	[enum_mob.serpent_eau]: 'https://ideo-lejeu.com/ideov23/creatures/serpent_deau.png',
	[enum_mob.shak]: 'https://ideo-lejeu.com/ideov23/creatures/shak.png',
	[enum_mob.skaven]: 'https://ideo-lejeu.com/ideov23/creatures/skaven.png',
	[enum_mob.slaad_mineur]: 'https://ideo-lejeu.com/ideov23/creatures/slaad_mineur.png',
	[enum_mob.slaad_mineur_gris]: 'https://ideo-lejeu.com/ideov23/creatures/slaad_mineur_gris.png',
	[enum_mob.slaad_mineur_vert]: 'https://ideo-lejeu.com/ideov23/creatures/slaad_mineur_vert.png',
	[enum_mob.squelette_forcene]: 'https://ideo-lejeu.com/ideov23/creatures/squelette_forcene.png',
	[enum_mob.svrisslish_troll_glaces]: 'https://ideo-lejeu.com/ideov23/creatures/svrisslish_le_troll_des_glaces.png',
	[enum_mob.ogre]: 'https://ideo-lejeu.com/ideov23/creatures/ogre.png',
	[enum_mob.tekumbo]: 'https://ideo-lejeu.com/ideov23/creatures/tekumbo.png',
	[enum_mob.troll]: 'https://ideo-lejeu.com/ideov23/creatures/troll.png',
};
